[versions]
acra = "5.11.3"
androidJunit5 = "1.8.2.1"
appcompat = "1.7.0"
coil3 = "3.0.4"
commonsIo = "2.5" # 2.6 crashes the application on Android below 8, because java.nio.file is not available in these versions
composeUi = "1.7.6"
downloadPlugin = "5.6.0"
gradle = "8.13.2"
hiltAndroid = "2.55"
hiltNavigataionCompose = "1.2.0"
hiltWork = "1.2.0"
junitJupiter = "5.10.1"
kotlin = "2.1.0"
kotlinxCoroutines = "1.8.1"
kotlinxSerializationJson = "1.6.3"
kspPlugin = '2.1.0-1.0.29'
lifecycle = "2.8.7"
lifecycleExtensions = "2.2.0"
material = "1.12.0"
material3Android = "1.3.1"
materialIcons = "1.7.6"
navigationCompose = "2.8.9"
okhttp = "4.12.0"
preference = "1.2.1"
room = "2.6.1"
timber = "5.0.1"
work = "2.9.0"

[libraries]
acra-mail = { module = "ch.acra:acra-mail", version.ref = "acra" }
acra-notification = { module = "ch.acra:acra-notification", version.ref = "acra" }
android-junit5 = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "androidJunit5" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigataionCompose"}
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcons" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-navigation-compose = { module ="androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3"}
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
download-plugin = { id = "de.undercouch.download", version.ref = "downloadPlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }